title: El Nacimiento de Una Nueva Economía Global
description: ¿Qué pasaría si las reglas que definieron los últimos 40 años de la historia económica fueran desarrollos contingentes de una sola vez, que ahora están llegando rápidamente a su fin?
theme: jekyll-theme-slate
markdown: kramdown
url: "https://juliocedillo.github.io"
baseurl: "/neweconomy-es"
logo: "https://juliocedillo.github.io/neweconomy/assets/images/seal.ico"
